"""Primeira migração

Revision ID: a1aa5e913f48
Revises: 
Create Date: 2026-09-08 00:02:35.719186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1aa5e913f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id_funcionario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id_funcionario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('material',
    sa.Column('id_material', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('retirada',
    sa.Column('id_retirada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_retirada', sa.DateTime(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionario.id_funcionario'], ),
    sa.PrimaryKeyConstraint('id_retirada')
    )
    op.create_table('item_retirada',
    sa.Column('id_retirada', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['material.id_material'], ),
    sa.ForeignKeyConstraint(['id_retirada'], ['retirada.id_retirada'], ),
    sa.PrimaryKeyConstraint('id_retirada', 'id_material')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_retirada')
    op.drop_table('retirada')
    op.drop_table('material')
    op.drop_table('funcionario')
    # ### end Alembic commands ###
